//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP = new HashSet<CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP>();
            this.SPACE_UTILISATION = new HashSet<SPACE_UTILISATION>();
            this.INTERNSHIP_PROJECT_FOR_OVERSEAS = new HashSet<INTERNSHIP_PROJECT_FOR_OVERSEAS>();
            this.MENTOR_DETAIL = new HashSet<MENTOR_DETAIL>();
        }
    
        public decimal COMPANY_ID { get; set; }
        public string UEN { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_DESCRIPTION { get; set; }
        public decimal COUNTRY_ID { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP> CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP { get; set; }
        public virtual ICollection<SPACE_UTILISATION> SPACE_UTILISATION { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT_FOR_OVERSEAS> INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
        public virtual ICollection<MENTOR_DETAIL> MENTOR_DETAIL { get; set; }
    }
}
