//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP
    {
        public decimal PROJECT_ID { get; set; }
        public string STUDENT_ID_NUMBER { get; set; }
        public decimal SCHOOL_ID { get; set; }
        public decimal COURSE_ID { get; set; }
        public decimal ACADEMIC_YEAR_ID { get; set; }
        public decimal SEMESTER_ID { get; set; }
        public decimal YEAR_OF_STUDY_ID { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> TRAINING_HOURS { get; set; }
        public string OVERSEAS_OR_LOCAL { get; set; }
        public decimal COUNTRY_ID { get; set; }
    
        public virtual ACADEMIC_YEAR ACADEMIC_YEAR { get; set; }
        public virtual CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual COURSE COURSE { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual YEAR_OF_STUDY YEAR_OF_STUDY { get; set; }
    }
}
