//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public COUNTRY()
        {
            this.COMPANies = new HashSet<COMPANY>();
            this.CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP = new HashSet<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP>();
            this.ELEARNING_OVERSEAS_PARTNER = new HashSet<ELEARNING_OVERSEAS_PARTNER>();
            this.EVENTS = new HashSet<EVENT>();
            this.GLP_PROGRAMME = new HashSet<GLP_PROGRAMME>();
            this.INTERNSHIP_PROJECT_FOR_OVERSEAS = new HashSet<INTERNSHIP_PROJECT_FOR_OVERSEAS>();
            this.INVESTORs = new HashSet<INVESTOR>();
            this.MENTOR_DETAIL = new HashSet<MENTOR_DETAIL>();
            this.OVERSEAS_LO_RELATIONSHIP = new HashSet<OVERSEAS_LO_RELATIONSHIP>();
        }
    
        public decimal COUNTRY_ID { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_NAME { get; set; }
    
        public virtual ICollection<COMPANY> COMPANies { get; set; }
        public virtual ICollection<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP> CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP { get; set; }
        public virtual ICollection<ELEARNING_OVERSEAS_PARTNER> ELEARNING_OVERSEAS_PARTNER { get; set; }
        public virtual ICollection<EVENT> EVENTS { get; set; }
        public virtual ICollection<GLP_PROGRAMME> GLP_PROGRAMME { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT_FOR_OVERSEAS> INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
        public virtual ICollection<INVESTOR> INVESTORs { get; set; }
        public virtual ICollection<MENTOR_DETAIL> MENTOR_DETAIL { get; set; }
        public virtual ICollection<OVERSEAS_LO_RELATIONSHIP> OVERSEAS_LO_RELATIONSHIP { get; set; }
    }
}
