//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP = new HashSet<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP>();
            this.STUDENT_DETAIL_ELEARNING_LOCAL = new HashSet<STUDENT_DETAIL_ELEARNING_LOCAL>();
        }
    
        public decimal COURSE_ID { get; set; }
        public string COURSE_NUMBER { get; set; }
        public string COURSE_NAME { get; set; }
        public string COURSE_DESCRIPTION { get; set; }
    
        public virtual ICollection<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP> CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP { get; set; }
        public virtual ICollection<STUDENT_DETAIL_ELEARNING_LOCAL> STUDENT_DETAIL_ELEARNING_LOCAL { get; set; }
    }
}
