//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DASHBOARD_TYPE
    {
        public DASHBOARD_TYPE()
        {
            this.ACCOUNT_DASHBOARD_RELATIONSHIP = new HashSet<ACCOUNT_DASHBOARD_RELATIONSHIP>();
            this.CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP = new HashSet<CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP>();
            this.GLP_PROGRAMME = new HashSet<GLP_PROGRAMME>();
            this.INTERNSHIP_PROJECT = new HashSet<INTERNSHIP_PROJECT>();
            this.INTERNSHIP_PROJECT_FOR_OVERSEAS = new HashSet<INTERNSHIP_PROJECT_FOR_OVERSEAS>();
            this.STARTUP_DETAIL = new HashSet<STARTUP_DETAIL>();
        }
    
        public decimal DASHBOARD_TYPE_ID { get; set; }
        public string DASHBOARD_TYPE_NAME { get; set; }
        public string DASHBOARD_TYPE_DESCRIPTION { get; set; }
    
        public virtual ICollection<ACCOUNT_DASHBOARD_RELATIONSHIP> ACCOUNT_DASHBOARD_RELATIONSHIP { get; set; }
        public virtual ICollection<CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP> CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP { get; set; }
        public virtual ICollection<GLP_PROGRAMME> GLP_PROGRAMME { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT> INTERNSHIP_PROJECT { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT_FOR_OVERSEAS> INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
        public virtual ICollection<STARTUP_DETAIL> STARTUP_DETAIL { get; set; }
    }
}
