//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEARNING_OVERSEAS_PARTNER
    {
        public decimal ELEARNING_OVERSEAS_PARTNER_ID { get; set; }
        public string PARTNER_NAME { get; set; }
        public string CONTACT_PERSON { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public Nullable<System.DateTime> MOU_START_DATE { get; set; }
        public Nullable<System.DateTime> MOU_END_DATE { get; set; }
        public Nullable<System.DateTime> BILLING_DATE { get; set; }
        public Nullable<decimal> BILLING_AMOUNT { get; set; }
        public Nullable<int> NO_OF_STUDENTS { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
    }
}
