//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public decimal EVENT_ID { get; set; }
        public string EVENT_NAME { get; set; }
        public string ORGANIZED_BY { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public Nullable<System.DateTime> EVENT_DATE { get; set; }
        public Nullable<int> NO_OF_STUDENTS { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
    }
}
