//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNAL_CONSULTANCT_PROJECT_RELATIONSHIP
    {
        public decimal PROJECT_ID { get; set; }
        public string EXTERNAL_CONSULTANT_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> MAN_HOURS { get; set; }
        public Nullable<decimal> FEE { get; set; }
    
        public virtual CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP { get; set; }
    }
}
