//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLP_PROGRAMME_TRAINER
    {
        public decimal GLP_PROGRAMME_TRAINER_ID { get; set; }
        public decimal PROGRAMME_ID { get; set; }
        public string TRAINER { get; set; }
        public string AFFILIATION { get; set; }
        public string RATE { get; set; }
        public Nullable<decimal> GLP_TRAINING_TYPE_ID { get; set; }
        public Nullable<bool> LEAVE { get; set; }
        public Nullable<decimal> HOURLY_RATE { get; set; }
        public Nullable<decimal> TOTAL_HOURS { get; set; }
        public Nullable<decimal> TOTAL_DAYS { get; set; }
        public Nullable<decimal> TOTAL_PAYABLE_FOR_TRAINER { get; set; }
        public Nullable<decimal> TOTAL_PAYABLE_FOR_SCHOOL { get; set; }
        public Nullable<decimal> TOTAL_PAYABLE_FOR_SPI { get; set; }
    
        public virtual GLP_PROGRAMME GLP_PROGRAMME { get; set; }
        public virtual GLP_TRAINING_TYPE GLP_TRAINING_TYPE { get; set; }
    }
}
