//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLP_TRAINING_TYPE
    {
        public GLP_TRAINING_TYPE()
        {
            this.GLP_PROGRAMME_TRAINER = new HashSet<GLP_PROGRAMME_TRAINER>();
        }
    
        public decimal GLP_TRAINING_TYPE_ID { get; set; }
        public string GLP_TRAINING_TYPE_NAME { get; set; }
        public string GLP_TRAINING_TYPE_DECRIPTION { get; set; }
    
        public virtual ICollection<GLP_PROGRAMME_TRAINER> GLP_PROGRAMME_TRAINER { get; set; }
    }
}
