//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLP_THEME
    {
        public GLP_THEME()
        {
            this.GLP_PROGRAMME = new HashSet<GLP_PROGRAMME>();
        }
    
        public decimal GLP_THEME_ID { get; set; }
        public string GLP_THEME_NAME { get; set; }
        public string GLP_THEME_DECRIPTION { get; set; }
    
        public virtual ICollection<GLP_PROGRAMME> GLP_PROGRAMME { get; set; }
    }
}
