//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLP_PROGRAMME
    {
        public GLP_PROGRAMME()
        {
            this.GLP_PROGRAMME_TRAINER = new HashSet<GLP_PROGRAMME_TRAINER>();
        }
    
        public decimal PROGRAMME_ID { get; set; }
        public string PROGRAMME_ID_NUMBER { get; set; }
        public string PROGRAMME_NAME { get; set; }
        public Nullable<decimal> GLP_THEME_ID { get; set; }
        public decimal SCHOOL_ID { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> NO_OF_STUDENTS { get; set; }
        public Nullable<decimal> STUDENT_FEEDBACK_SCORE { get; set; }
        public Nullable<decimal> TOTAL_FUNDING { get; set; }
        public Nullable<decimal> TOTAL_EXPENSES { get; set; }
        public decimal DASHBOARD_TYPE_ID { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual DASHBOARD_TYPE DASHBOARD_TYPE { get; set; }
        public virtual GLP_THEME GLP_THEME { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
        public virtual ICollection<GLP_PROGRAMME_TRAINER> GLP_PROGRAMME_TRAINER { get; set; }
    }
}
