//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNSHIP_PROJECT_FOR_OVERSEAS
    {
        public INTERNSHIP_PROJECT_FOR_OVERSEAS()
        {
            this.INTERNSHIP_PROJECT_FOR_OVERSEAS_STUDENT_RELATIONSHIP = new HashSet<INTERNSHIP_PROJECT_FOR_OVERSEAS_STUDENT_RELATIONSHIP>();
            this.OVERSEAS_LO_RELATIONSHIP = new HashSet<OVERSEAS_LO_RELATIONSHIP>();
        }
    
        public decimal PROJECT_ID { get; set; }
        public string PROJECT_REFERENCE { get; set; }
        public decimal INTERNSHIP_PROJECT_TYPE_ID { get; set; }
        public decimal PROJECT_AREA_ID { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public decimal COMPANY_ID { get; set; }
        public string PROJECT_SUPERVISOR { get; set; }
        public Nullable<System.DateTime> PROJECT_ACCEPTANCE_DATE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> REVENUE { get; set; }
        public Nullable<decimal> EXPENSES { get; set; }
        public decimal PROJECT_STATUS_ID { get; set; }
        public decimal DASHBOARD_TYPE_ID { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual DASHBOARD_TYPE DASHBOARD_TYPE { get; set; }
        public virtual INTERNSHIP_PROJECT_TYPE INTERNSHIP_PROJECT_TYPE { get; set; }
        public virtual PROJECT_AREA PROJECT_AREA { get; set; }
        public virtual PROJECT_STATUS PROJECT_STATUS { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT_FOR_OVERSEAS_STUDENT_RELATIONSHIP> INTERNSHIP_PROJECT_FOR_OVERSEAS_STUDENT_RELATIONSHIP { get; set; }
        public virtual ICollection<OVERSEAS_LO_RELATIONSHIP> OVERSEAS_LO_RELATIONSHIP { get; set; }
    }
}
