//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNSHIP_PROJECT_FOR_OVERSEAS_STUDENT_RELATIONSHIP
    {
        public decimal PROJECT_ID { get; set; }
        public string STUDENT_ID_NUMBER { get; set; }
        public Nullable<bool> SP_OR_COUNTRY { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public decimal SCHOOL_ID { get; set; }
        public string DIPLOMA { get; set; }
        public decimal ACADEMIC_YEAR_ID { get; set; }
        public decimal SEMESTER_ID { get; set; }
        public decimal YEAR_OF_STUDY_ID { get; set; }
        public Nullable<decimal> PROGRAMME_FEEDBACK_AVE_SCORE { get; set; }
    
        public virtual INTERNSHIP_PROJECT_FOR_OVERSEAS INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
