//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNSHIP_PROJECT_TYPE
    {
        public INTERNSHIP_PROJECT_TYPE()
        {
            this.INTERNSHIP_PROJECT = new HashSet<INTERNSHIP_PROJECT>();
            this.INTERNSHIP_PROJECT_FOR_OVERSEAS = new HashSet<INTERNSHIP_PROJECT_FOR_OVERSEAS>();
        }
    
        public decimal INTERNSHIP_PROJECT_TYPE_ID { get; set; }
        public string INTERNSHIP_PROJECT_TYPE_NAME { get; set; }
        public string INTERNSHIP_PROJECT_TYPE_DESCRIPTION { get; set; }
    
        public virtual ICollection<INTERNSHIP_PROJECT> INTERNSHIP_PROJECT { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT_FOR_OVERSEAS> INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
    }
}
