//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNSHIP_PROJECT_STUDENT_RELATIONSHIP
    {
        public decimal INTERNSHIP_ID { get; set; }
        public string STUDENT_ID_NUMBER { get; set; }
        public Nullable<decimal> LO_ID { get; set; }
        public decimal SCHOOL_ID { get; set; }
        public decimal COURSE_ID { get; set; }
        public decimal ACADEMIC_YEAR_ID { get; set; }
        public decimal SEMESTER_ID { get; set; }
        public decimal YEAR_OF_STUDY_ID { get; set; }
        public Nullable<decimal> COST_TO_SP { get; set; }
    
        public virtual INTERNSHIP_PROJECT INTERNSHIP_PROJECT { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
