//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERNSHIP_PROJECT
    {
        public INTERNSHIP_PROJECT()
        {
            this.INTERNSHIP_PROJECT_STUDENT_RELATIONSHIP = new HashSet<INTERNSHIP_PROJECT_STUDENT_RELATIONSHIP>();
        }
    
        public decimal INTERNSHIP_ID { get; set; }
        public string INTERNSHIP_REFERENCE { get; set; }
        public decimal INTERNSHIP_PROJECT_TYPE_ID { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public decimal COMPANY_ID { get; set; }
        public string CONTACT_PERSON { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<int> NO_OF_STUDENTS { get; set; }
        public Nullable<decimal> COST_TO_SP { get; set; }
        public decimal DASHBOARD_TYPE_ID { get; set; }
    
        public virtual DASHBOARD_TYPE DASHBOARD_TYPE { get; set; }
        public virtual INTERNSHIP_PROJECT_TYPE INTERNSHIP_PROJECT_TYPE { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT_STUDENT_RELATIONSHIP> INTERNSHIP_PROJECT_STUDENT_RELATIONSHIP { get; set; }
    }
}
