//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTOR
    {
        public INVESTOR()
        {
            this.STARTUP_INVESTOR_RELATIONSHIP = new HashSet<STARTUP_INVESTOR_RELATIONSHIP>();
        }
    
        public decimal INVESTOR_ID { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public string MENTOR_NAME { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual ICollection<STARTUP_INVESTOR_RELATIONSHIP> STARTUP_INVESTOR_RELATIONSHIP { get; set; }
    }
}
