//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENTOR_DETAIL
    {
        public MENTOR_DETAIL()
        {
            this.STARTUP_DETAIL = new HashSet<STARTUP_DETAIL>();
        }
    
        public decimal MENTOR_ID { get; set; }
        public string MENTOR_NAME { get; set; }
        public decimal MENTOR_GROUP_ID { get; set; }
        public decimal MENTOR_TYPE_ID { get; set; }
        public Nullable<decimal> SCHOOL_ID { get; set; }
        public Nullable<decimal> COMPANY_ID { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public decimal REMUNERATION_TYPE_ID { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual MENTOR_GROUP MENTOR_GROUP { get; set; }
        public virtual MENTOR_TYPE MENTOR_TYPE { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
        public virtual REMUNERATION_TYPE REMUNERATION_TYPE { get; set; }
        public virtual ICollection<STARTUP_DETAIL> STARTUP_DETAIL { get; set; }
    }
}
