//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULE
    {
        public MODULE()
        {
            this.FUNCTIONS = new HashSet<FUNCTION>();
        }
    
        public decimal MODULE_ID { get; set; }
        public string MODULE_NAME { get; set; }
        public string MODULE_FORM_URL { get; set; }
    
        public virtual ICollection<FUNCTION> FUNCTIONS { get; set; }
    }
}
