//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVERSEAS_LO_RELATIONSHIP
    {
        public decimal LO_ID { get; set; }
        public decimal PROJECT_ID { get; set; }
        public Nullable<bool> SP_OR_COUNTRY { get; set; }
        public decimal COUNTRY_ID { get; set; }
        public decimal SCHOOL_ID { get; set; }
        public string STAFF_ID_NUMBER { get; set; }
        public Nullable<bool> LO_TRAINING { get; set; }
        public Nullable<decimal> LO_FEEDBACK_SCORE { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual INTERNSHIP_PROJECT_FOR_OVERSEAS INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
    }
}
