//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_AREA
    {
        public PROJECT_AREA()
        {
            this.INTERNSHIP_PROJECT_FOR_OVERSEAS = new HashSet<INTERNSHIP_PROJECT_FOR_OVERSEAS>();
        }
    
        public decimal PROJECT_AREA_ID { get; set; }
        public string PROJECT_AREA_NAME { get; set; }
        public string PROJECT_AREA_DESCRIPTION { get; set; }
    
        public virtual ICollection<INTERNSHIP_PROJECT_FOR_OVERSEAS> INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
    }
}
