//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_STATUS
    {
        public PROJECT_STATUS()
        {
            this.CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP = new HashSet<CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP>();
            this.INTERNSHIP_PROJECT_FOR_OVERSEAS = new HashSet<INTERNSHIP_PROJECT_FOR_OVERSEAS>();
        }
    
        public decimal PROJECT_STATUS_ID { get; set; }
        public string PROJECT_STATUS_NAME { get; set; }
        public string PROJECT_STATUS_DESCRIPTION { get; set; }
    
        public virtual ICollection<CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP> CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP { get; set; }
        public virtual ICollection<INTERNSHIP_PROJECT_FOR_OVERSEAS> INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
    }
}
