//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOL
    {
        public SCHOOL()
        {
            this.CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP = new HashSet<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP>();
            this.GLP_PROGRAMME = new HashSet<GLP_PROGRAMME>();
            this.MENTOR_DETAIL = new HashSet<MENTOR_DETAIL>();
            this.OVERSEAS_LO_RELATIONSHIP = new HashSet<OVERSEAS_LO_RELATIONSHIP>();
            this.STUDENT_DETAIL_ELEARNING_LOCAL = new HashSet<STUDENT_DETAIL_ELEARNING_LOCAL>();
        }
    
        public decimal SCHOOL_ID { get; set; }
        public string SCHOOL_NAME { get; set; }
        public string SCHOOL_DESCRIPTION { get; set; }
        public decimal COUNTRY_ID { get; set; }
    
        public virtual ICollection<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP> CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP { get; set; }
        public virtual ICollection<GLP_PROGRAMME> GLP_PROGRAMME { get; set; }
        public virtual ICollection<MENTOR_DETAIL> MENTOR_DETAIL { get; set; }
        public virtual ICollection<OVERSEAS_LO_RELATIONSHIP> OVERSEAS_LO_RELATIONSHIP { get; set; }
        public virtual ICollection<STUDENT_DETAIL_ELEARNING_LOCAL> STUDENT_DETAIL_ELEARNING_LOCAL { get; set; }
    }
}
