//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPACE_UTILISATION
    {
        public decimal COMPANY_DETAILS_ID { get; set; }
        public decimal COMPANY_ID { get; set; }
        public decimal TYPE_ACCES_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual TYPE_OF_ACCES TYPE_OF_ACCES { get; set; }
    }
}
