//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SP_DASHBOARDEntities : DbContext
    {
        public SP_DASHBOARDEntities()
            : base("name=SP_DASHBOARDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACADEMIC_YEAR> ACADEMIC_YEAR { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ACCOUNT_DASHBOARD_RELATIONSHIP> ACCOUNT_DASHBOARD_RELATIONSHIP { get; set; }
        public virtual DbSet<ACCOUNT_FUNCTION_RELATIONSHIP> ACCOUNT_FUNCTION_RELATIONSHIP { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<CONSULTANCE_PROJECT_STAFF_RELATIONSHIP> CONSULTANCE_PROJECT_STAFF_RELATIONSHIP { get; set; }
        public virtual DbSet<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP> CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP { get; set; }
        public virtual DbSet<CONSULTANCY_CENTRE> CONSULTANCY_CENTRE { get; set; }
        public virtual DbSet<CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP> CONSULTANCY_CENTRE_PROJECT_RELATIONSHIP { get; set; }
        public virtual DbSet<CONSULTANCY_PROJECT_TYPE> CONSULTANCY_PROJECT_TYPE { get; set; }
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<DASHBOARD_TYPE> DASHBOARD_TYPE { get; set; }
        public virtual DbSet<ELEARNING_OVERSEAS_PARTNER> ELEARNING_OVERSEAS_PARTNER { get; set; }
        public virtual DbSet<EVENT> EVENTS { get; set; }
        public virtual DbSet<EXTERNAL_CONSULTANCT_PROJECT_RELATIONSHIP> EXTERNAL_CONSULTANCT_PROJECT_RELATIONSHIP { get; set; }
        public virtual DbSet<FUNCTION> FUNCTIONS { get; set; }
        public virtual DbSet<GLP_PROGRAMME> GLP_PROGRAMME { get; set; }
        public virtual DbSet<GLP_PROGRAMME_TRAINER> GLP_PROGRAMME_TRAINER { get; set; }
        public virtual DbSet<GLP_THEME> GLP_THEME { get; set; }
        public virtual DbSet<GLP_TRAINING_TYPE> GLP_TRAINING_TYPE { get; set; }
        public virtual DbSet<INTERNSHIP_PROJECT> INTERNSHIP_PROJECT { get; set; }
        public virtual DbSet<INTERNSHIP_PROJECT_FOR_OVERSEAS> INTERNSHIP_PROJECT_FOR_OVERSEAS { get; set; }
        public virtual DbSet<INTERNSHIP_PROJECT_FOR_OVERSEAS_STUDENT_RELATIONSHIP> INTERNSHIP_PROJECT_FOR_OVERSEAS_STUDENT_RELATIONSHIP { get; set; }
        public virtual DbSet<INTERNSHIP_PROJECT_STUDENT_RELATIONSHIP> INTERNSHIP_PROJECT_STUDENT_RELATIONSHIP { get; set; }
        public virtual DbSet<INTERNSHIP_PROJECT_TYPE> INTERNSHIP_PROJECT_TYPE { get; set; }
        public virtual DbSet<INVESTOR> INVESTORs { get; set; }
        public virtual DbSet<MENTOR_DETAIL> MENTOR_DETAIL { get; set; }
        public virtual DbSet<MENTOR_GROUP> MENTOR_GROUP { get; set; }
        public virtual DbSet<MENTOR_TYPE> MENTOR_TYPE { get; set; }
        public virtual DbSet<MODULE> MODULES { get; set; }
        public virtual DbSet<OVERSEAS_LO_RELATIONSHIP> OVERSEAS_LO_RELATIONSHIP { get; set; }
        public virtual DbSet<PROJECT_AREA> PROJECT_AREA { get; set; }
        public virtual DbSet<PROJECT_STATUS> PROJECT_STATUS { get; set; }
        public virtual DbSet<REMUNERATION_TYPE> REMUNERATION_TYPE { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SCHOOL> SCHOOLs { get; set; }
        public virtual DbSet<SEMESTER> SEMESTERs { get; set; }
        public virtual DbSet<SPACE_UTILISATION> SPACE_UTILISATION { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STARTUP_DETAIL> STARTUP_DETAIL { get; set; }
        public virtual DbSet<STARTUP_INVESTOR_RELATIONSHIP> STARTUP_INVESTOR_RELATIONSHIP { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
        public virtual DbSet<STUDENT_DETAIL_ELEARNING_LOCAL> STUDENT_DETAIL_ELEARNING_LOCAL { get; set; }
        public virtual DbSet<TYPE_OF_ACCES> TYPE_OF_ACCES { get; set; }
        public virtual DbSet<YEAR_OF_STUDY> YEAR_OF_STUDY { get; set; }
    }
}
