//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.CONSULTANCE_PROJECT_STAFF_RELATIONSHIP = new HashSet<CONSULTANCE_PROJECT_STAFF_RELATIONSHIP>();
        }
    
        public string STAFF_ID_NUMBER { get; set; }
        public string STAFF_FIRST_NAME { get; set; }
        public string STAFF_MIDDLE_NAME { get; set; }
        public string STAFF_LAST_NAME { get; set; }
        public string STAFF_DESCRIPTION { get; set; }
    
        public virtual ICollection<CONSULTANCE_PROJECT_STAFF_RELATIONSHIP> CONSULTANCE_PROJECT_STAFF_RELATIONSHIP { get; set; }
    }
}
