//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STARTUP_DETAIL
    {
        public STARTUP_DETAIL()
        {
            this.STARTUP_INVESTOR_RELATIONSHIP = new HashSet<STARTUP_INVESTOR_RELATIONSHIP>();
            this.MENTOR_DETAIL = new HashSet<MENTOR_DETAIL>();
        }
    
        public string STARTUP_ID { get; set; }
        public string STARTUP_NAME { get; set; }
        public string TEAM_LEADER { get; set; }
        public Nullable<System.DateTime> STARTUP_DATE { get; set; }
        public string STAGE { get; set; }
        public Nullable<bool> FUNDED { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<bool> COMPANY_REGISTERED { get; set; }
        public decimal DASHBOARD_TYPE_ID { get; set; }
    
        public virtual DASHBOARD_TYPE DASHBOARD_TYPE { get; set; }
        public virtual ICollection<STARTUP_INVESTOR_RELATIONSHIP> STARTUP_INVESTOR_RELATIONSHIP { get; set; }
        public virtual ICollection<MENTOR_DETAIL> MENTOR_DETAIL { get; set; }
    }
}
