//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STARTUP_INVESTOR_RELATIONSHIP
    {
        public string STARTUP_ID { get; set; }
        public decimal INVESTOR_ID { get; set; }
        public Nullable<decimal> AMOUNT_INVESTOR { get; set; }
        public Nullable<System.DateTime> DATE_OF_INVESTMENT { get; set; }
    
        public virtual INVESTOR INVESTOR { get; set; }
        public virtual STARTUP_DETAIL STARTUP_DETAIL { get; set; }
    }
}
