//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_DETAIL_ELEARNING_LOCAL
    {
        public decimal STUDENT_DETAIL_ID { get; set; }
        public string STUDENT_ID_NUMBER { get; set; }
        public string MODULE_CODE { get; set; }
        public decimal SCHOOL_ID { get; set; }
        public decimal COURSE_ID { get; set; }
        public decimal ACADEMIC_YEAR_ID { get; set; }
        public decimal SEMESTER_ID { get; set; }
        public string STATUS { get; set; }
    
        public virtual ACADEMIC_YEAR ACADEMIC_YEAR { get; set; }
        public virtual COURSE COURSE { get; set; }
        public virtual SCHOOL SCHOOL { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
