//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_OF_ACCES
    {
        public TYPE_OF_ACCES()
        {
            this.SPACE_UTILISATION = new HashSet<SPACE_UTILISATION>();
        }
    
        public decimal TYPE_ACCES_ID { get; set; }
        public string TYPE_ACCES_NAME { get; set; }
        public string DECRIPTION { get; set; }
    
        public virtual ICollection<SPACE_UTILISATION> SPACE_UTILISATION { get; set; }
    }
}
