//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEAR_OF_STUDY
    {
        public YEAR_OF_STUDY()
        {
            this.CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP = new HashSet<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP>();
        }
    
        public decimal YEAR_OF_STUDY_ID { get; set; }
        public string YEAR_OF_STUDY_NAME { get; set; }
        public string YEAR_OF_STUDY_DESCRIPTION { get; set; }
    
        public virtual ICollection<CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP> CONSULTANCE_PROJECT_STUDENT_RELATIONSHIP { get; set; }
    }
}
